#ifndef ABURI_BUILTIN_REGISTRY_H
#define ABURI_BUILTIN_REGISTRY_H

#include <string>
#include <string_view>
#include <unordered_map>

enum class BuiltinKind {
    EXPECT,
    CONSTANT_P,
    UNREACHABLE,
    TRAP,
    TYPES_COMPATIBLE_P,
    CHOOSE_EXPR,
    OBJECT_SIZE,
    DYNAMIC_OBJECT_SIZE,
    OFFSETOF,
    AVAILABLE,
    IS_CONSTANT_EVALUATED,
    IS_SAME,
    IS_FUNCTION,
    IS_REFERENCE,
    IS_LVALUE_REFERENCE,
    IS_RVALUE_REFERENCE,
    HAS_VIRTUAL_DESTRUCTOR,
    IS_ABSTRACT,
    IS_ARRAY,
    IS_BOUNDED_ARRAY,
    IS_UNION,
    IS_VOLATILE,
    IS_CONST,
    IS_EMPTY,
    IS_ENUM,
    IS_SCOPED_ENUM,
    IS_FUNDAMENTAL,
    IS_VOID,
    IS_INTEGRAL,
    IS_FLOATING_POINT,
    IS_ARITHMETIC,
    IS_SCALAR,
    IS_COMPOUND,
    IS_UNSIGNED,
    IS_ASSIGNABLE,
    IS_TRIVIALLY_ASSIGNABLE,
    IS_NOTHROW_ASSIGNABLE,
    IS_BASE_OF,
    IS_CLASS,
    IS_FINAL,
    IS_AGGREGATE,
    IS_MEMBER_POINTER,
    IS_MEMBER_OBJECT_POINTER,
    IS_MEMBER_FUNCTION_POINTER,
    IS_NULL_POINTER,
    IS_OBJECT,
    IS_POINTER,
    IS_POLYMORPHIC,
    IS_STANDARD_LAYOUT,
    IS_TRIVIAL,
    IS_TRIVIALLY_COPYABLE,
    HAS_UNIQUE_OBJECT_REPRESENTATIONS,
    IS_POD,
    IS_SIGNED,
    IS_CONSTRUCTIBLE,
    IS_TRIVIALLY_CONSTRUCTIBLE,
    IS_NOTHROW_CONSTRUCTIBLE,
    IS_CONVERTIBLE,
    IS_CORE_CONVERTIBLE,
    IS_NOTHROW_CONVERTIBLE,
    REFERENCE_BINDS_TO_TEMPORARY,
    IS_DESTRUCTIBLE,
    IS_NOTHROW_DESTRUCTIBLE,
    IS_TRIVIALLY_DESTRUCTIBLE,
    HAS_TRIVIAL_DESTRUCTOR,
    IS_LITERAL_TYPE,
    INTEGER_PACK,
    MAKE_INTEGER_SEQ,
    REMOVE_CONST,
    REMOVE_VOLATILE,
    REMOVE_CV,
    REMOVE_CVREF,
    REMOVE_REFERENCE,
    UNDERLYING_TYPE,
    REMOVE_EXTENT,
    REMOVE_ALL_EXTENTS,
    ADD_LVALUE_REFERENCE,
    ADD_RVALUE_REFERENCE,
    ADD_POINTER,
    DECAY,

    ADD_OVERFLOW,
    SUB_OVERFLOW,
    MUL_OVERFLOW,
    ADD_OVERFLOW_P,
    SUB_OVERFLOW_P,
    CLZ,
    CLZL,
    CLZLL,
    CTZ,
    CTZL,
    CTZLL,
    FFS,
    FFSL,
    FFSLL,
    POPCOUNT,
    POPCOUNTL,
    POPCOUNTLL,
    BSWAP16,
    BSWAP32,
    BSWAP64,
    IA32_BZHI_SI,
    ADDRESSOF,
    STPCPY,
    MEMPCPY,
    MEMCPY,
    MEMMOVE,
    MEMSET,
    MEMCMP,
    MEMCMP_EQ,
    MEMCHR,
    BCOPY,
    BZERO,
    STRCMP,
    STRNCMP,
    STRLEN,
    STRCPY,
    STRNCPY,
    STRCAT,
    STRNCAT,
    STRCSPN,
    STRSPN,
    STRCHR,
    STRRCHR,
    STRSTR,
    STRDUP,
    STPNCPY,
    STRNDUP,
    STRNCASECMP,

    MEMCPY_CHK,
    MEMMOVE_CHK,
    MEMSET_CHK,
    STRNCPY_CHK,
    STRCPY_CHK,
    STPCPY_CHK,
    STRCAT_CHK,
    STRNCAT_CHK,
    SPRINTF_CHK,
    SNPRINTF_CHK,
    VSPRINTF_CHK,
    VSNPRINTF_CHK,

    CLEAR_CACHE,
    CLEAR_PADDING,
    PREFETCH,
    RETURN_ADDRESS,
    FRAME_ADDRESS,
    EXTRACT_RETURN_ADDR,
    ALLOCA,
    STACK_SAVE,
    STACK_RESTORE,
    FLT_ROUNDS,
    ISNAN,
    ISINF,
    ISINF_SIGN,
    ISFINITE,
    ISNORMAL,
    FPCLASSIFY,
    ISEQSIG,
    BUILTIN_HUGE_VAL,
    BUILTIN_HUGE_VALF,
    INF,
    INFF,
    INFL,
    BUILTIN_HUGE_VALL,
    NAN_BUILTIN,
    NANF,
    NANL,
    NANS,
    NANSF,
    NANSL,
    ABS,
    LABS,
    LLABS,
    FABS,
    FABSF,
    FABSL,
    COMPLEX,
    CONJF,
    ILOGB,
    ILOGBF,
    ILOGBL,
    POW,
    POWF,
    POWL,
    CPOW,
    CEXPI,
    SQRT,
    SQRTF,
    SQRTL,
    CBRT,
    CBRTF,
    CBRTL,
    SIN,
    SINF,
    SINL,
    COS,
    COSF,
    COSL,
    TAN,
    TANF,
    TANL,
    ASIN,
    ASINF,
    ASINL,
    ACOS,
    ACOSF,
    ACOSL,
    ATAN,
    ATANF,
    ATANL,
    ATAN2,
    ATAN2F,
    ATAN2L,
    SINH,
    SINHF,
    SINHL,
    COSH,
    COSHF,
    COSHL,
    TANH,
    TANHF,
    TANHL,
    ASINH,
    ASINHF,
    ASINHL,
    ACOSH,
    ACOSHF,
    ACOSHL,
    ATANH,
    ATANHF,
    ATANHL,
    LOG,
    LOGF,
    LOGL,
    LOG2,
    LOG2F,
    LOG2L,
    LOG10,
    LOG10F,
    LOG10L,
    LOG1P,
    LOG1PF,
    LOG1PL,
    LOGB,
    LOGBF,
    LOGBL,
    EXP,
    EXPF,
    EXPL,
    EXP2,
    EXP2F,
    EXP2L,
    EXPM1,
    EXPM1F,
    EXPM1L,
    FREXP,
    FREXPF,
    FREXPL,
    LDEXP,
    LDEXPF,
    LDEXPL,
    SCALBN,
    SCALBNF,
    SCALBNL,
    SCALBLN,
    SCALBLNF,
    SCALBLNL,
    CEIL,
    CEILF,
    CEILL,
    FLOOR,
    FLOORF,
    FLOORL,
    ROUND,
    ROUNDF,
    ROUNDL,
    RINT,
    RINTF,
    RINTL,
    NEARBYINT,
    NEARBYINTF,
    NEARBYINTL,
    LRINT,
    LRINTF,
    LRINTL,
    LROUND,
    LROUNDF,
    LROUNDL,
    LLRINT,
    LLRINTF,
    LLRINTL,
    LLROUND,
    LLROUNDF,
    LLROUNDL,
    COPYSIGN,
    COPYSIGNF,
    COPYSIGNL,
    HYPOT,
    HYPOTF,
    HYPOTL,
    FMIN,
    FMINF,
    FMINL,
    FMAX,
    FMAXF,
    FMAXL,
    FDIM,
    FDIMF,
    FDIML,
    FMA,
    FMAF,
    FMAL,
    FMOD,
    FMODF,
    FMODL,
    REMAINDER,
    REMAINDERF,
    REMAINDERL,
    REMQUO,
    REMQUOF,
    REMQUOL,
    NEXTAFTER,
    NEXTAFTERF,
    NEXTAFTERL,
    NEXTTOWARD,
    NEXTTOWARDF,
    NEXTTOWARDL,
    ERF,
    ERFF,
    ERFL,
    ERFC,
    ERFCF,
    ERFCL,
    LGAMMA,
    LGAMMAF,
    LGAMMAL,
    TGAMMA,
    TGAMMAF,
    TGAMMAL,

    MODF,
    MODFF,
    MODFL,
    TRUNC,
    TRUNCF,
    TRUNCL,

    SIGNBIT,
    SIGNBITF,
    SIGNBITL,

    ASSUME_ALIGNED,
    CLASSIFY_TYPE,
    EXPECT_WITH_PROBABILITY,
    BUILTIN_FILE,
    BUILTIN_LINE,
    BUILTIN_FUNCTION,
    CLRSB,
    CLRSBL,
    CLRSBLL,
    PARITY,
    PARITYL,
    PARITYLL,
    CONVERTVECTOR,
    SHUFFLEVECTOR,
    VA_START,
    VA_ARG,
    VA_END,
    VA_COPY,
    VA_ARG_PACK,
    ATOMIC_LOAD_N,
    ATOMIC_STORE_N,
    ATOMIC_EXCHANGE_N,
    ATOMIC_COMPARE_EXCHANGE_N,
    ATOMIC_IS_LOCK_FREE,
    ATOMIC_ALWAYS_LOCK_FREE,
    C11_ATOMIC_INIT,
    C11_ATOMIC_FETCH_ADD,
    C11_ATOMIC_FETCH_SUB,
    ATOMIC_FETCH_ADD,
    ATOMIC_FETCH_SUB,
    ATOMIC_FETCH_AND,
    ATOMIC_FETCH_OR,
    ATOMIC_FETCH_XOR,
    ATOMIC_FETCH_NAND,
    ATOMIC_ADD_FETCH,
    ATOMIC_SUB_FETCH,
    ATOMIC_AND_FETCH,
    ATOMIC_OR_FETCH,
    ATOMIC_XOR_FETCH,
    ATOMIC_NAND_FETCH,
    ATOMIC_THREAD_FENCE,
    ATOMIC_SIGNAL_FENCE,
    ATOMIC_TEST_AND_SET,
    ATOMIC_CLEAR,

    SYNC_FETCH_AND_ADD,
    SYNC_FETCH_AND_SUB,
    SYNC_FETCH_AND_OR,
    SYNC_FETCH_AND_AND,
    SYNC_FETCH_AND_XOR,
    SYNC_FETCH_AND_NAND,
    SYNC_ADD_AND_FETCH,
    SYNC_SUB_AND_FETCH,
    SYNC_OR_AND_FETCH,
    SYNC_AND_AND_FETCH,
    SYNC_XOR_AND_FETCH,
    SYNC_NAND_AND_FETCH,
    SYNC_BOOL_COMPARE_AND_SWAP,
    SYNC_VAL_COMPARE_AND_SWAP,
    SYNC_SYNCHRONIZE,
    SYNC_LOCK_TEST_AND_SET,
    SYNC_LOCK_RELEASE,

    PRINTF,
    PUTS,
    PUTCHAR,
    FPRINTF,
    SPRINTF,
    SNPRINTF,
    ISUNORDERED,
    ISLESS,
    ISLESSEQUAL,
    ISGREATER,
    ISGREATEREQUAL,
    ISLESSGREATER,

    MALLOC,
    CALLOC,
    REALLOC,
    FREE,
    OPERATOR_NEW,
    OPERATOR_DELETE,
    METAFN_QUERY_INT,
    METAFN_QUERY_INFO,
    METAFN_NAME_DATA,
    METAFN_NAME_SIZE,
    METAFN_RANGE_COUNT,
    METAFN_RANGE_AT,

    ABORT,
    EXIT,

    // The coroutine ABI must expose resume, destroy, promise, and state through
    // ordinary CIR so backends never depend on coroutine-specific operations.
    CORO_DONE,
    CORO_RESUME,
    CORO_DESTROY,
    CORO_PROMISE,

    BIT_CAST,
    TYPE_PACK_ELEMENT,

    REDUCE_AND,
    CLZG,
    CTZG,

    POPCOUNTG,

    SOURCE_LOCATION,
    LAUNDER,
};

enum class BuiltinSyntaxKind {
    Call,
    TypePredicate,
    TypeTrait,
    TypeTransform,
    IntegerSequenceType,
    ChooseExpr,
    Offsetof,
    VaArg,
    BitCast,
    ConvertVector,
    Available,
    PackElementType
};

struct BuiltinInfo {
    std::string_view name;
    BuiltinKind kind;
    int min_args;
    int max_args;
    bool takes_type_arg;
    bool is_compile_time_const;
    BuiltinSyntaxKind syntax = BuiltinSyntaxKind::Call;
    bool supported = false;
};

struct BuiltinLibcall {
    const char* callee;
    const char* signature;
};

const BuiltinLibcall* builtin_libcall(BuiltinKind kind);

class BuiltinRegistry {
public:
    static BuiltinRegistry& instance();

    const BuiltinInfo* lookup(std::string_view name) const;
    bool is_builtin(std::string_view name) const;
    bool is_supported(std::string_view name) const;

private:
    BuiltinRegistry();
    void register_builtin(BuiltinInfo info);

    std::unordered_map<std::string_view, BuiltinInfo> builtins;
};

bool is_builtin_type_trait_kind(BuiltinKind kind);
BuiltinSyntaxKind builtin_syntax_kind(BuiltinKind kind);
bool is_supported_builtin_kind(BuiltinKind kind);

#endif //ABURI_BUILTIN_REGISTRY_H
